using System;
using System.Collections.Generic;

namespace WWA.Core.Models
{
    /// <summary>
    /// Options flags for the packer.
    /// </summary>
    [Flags]
    public enum PackerOptions
    {
        None = 0,
        PreferLongRemnants = 1
    }

    /// <summary>
    /// Request object for the packer. Contains the cutlist, a snapshot of inventory and packing constraints.
    /// Example:
    /// var req = new PackingRequest { CutList = cutList, Inventory = inventory, Constraints = constraints, Seed = 42 };
    /// </summary>
    public class PackingRequest
    {
        public CutList CutList { get; set; } = new CutList();
        public Inventory Inventory { get; set; } = new Inventory();
        public Constraints Constraints { get; set; } = new Constraints();
        public int? Seed { get; set; }
        public PackerOptions Options { get; set; } = PackerOptions.None;
    }

    /// <summary>
    /// Result of a packing operation.
    /// </summary>
    public class PackingResult
    {
        /// <summary>
        /// Allocations by board.
        /// </summary>
        public List<BoardAllocation> Allocations { get; } = new List<BoardAllocation>();

        /// <summary>
        /// Leftover remnants (unused parts of boards) represented as Boards with remaining lengths.
        /// </summary>
        public List<Board> Leftovers { get; } = new List<Board>();

        /// <summary>
        /// Waste percent (0-100) computed as total leftover length divided by original total board length.
        /// </summary>
        public double WastePercent { get; set; }

        /// <summary>
        /// Total length used for cuts (in inches).
        /// </summary>
        public double TotalUsedLength { get; set; }

        /// <summary>
        /// The deterministic seed used by the packer (may be the provided seed or one generated by the packer).
        /// </summary>
        public int? DeterministicSeedUsed { get; set; }
    }

    /// <summary>
    /// Allocation of cut placements on a specific board.
    /// </summary>
    public class BoardAllocation
    {
        public Guid BoardId { get; set; }
        public double OriginalBoardLength { get; set; }
        public List<Placement> Placements { get; } = new List<Placement>();

        /// <summary>
        /// Remaining length after placements.
        /// </summary>
        public double RemnantLength { get; set; }
    }

    /// <summary>
    /// A placement of a CutItem on a board at an offset. Rotation indicates whether the item was rotated to fit.
    /// </summary>
    public class Placement
    {
        public Guid CutItemId { get; set; }
        public CutItem? CutItem { get; set; }
        public double Offset { get; set; }
        public bool Rotated { get; set; }
        public double Length { get; set; }
    }
}